### ISSUE TITLE
Package not found 

### ISSUE THREAD

**Issue by Simon-Delcamp** [autocorr/Jadex.jl#3]
Adding Jadex from Pkg does not work with Julia 1.7 in a fresh environment: 
```
Updating registry at ~/.julia/registries/General.toml
ERROR: The following package names could not be resolved:
 * Jadex (not found in project, manifest or registry) 
```

Using the github link to the project seems to work in a fresh environment. 

Also, the link to the documentation is down. Is it possible to have a new link?

**Comment by autocorr** [comment]
The README is currently incorrect since I haven't uploaded the package to the registry yet :) Sorry for the inconvenience. I planned on posting it once I've had more thorough validation/testing across all species and not just the HCO+ file that RADEX itself tests against.

The documentation is also trickier than expected to host with readthedocs, so I'll have to rig-up up Travis and GitHub pages according to the [Documenter.jl hosting instructions](https://juliadocs.github.io/Documenter.jl/stable/man/hosting/).

**Comment by autocorr** [comment]
The package should now be available through the package registry and the online documentation can now be found at https://autocorr.github.io/Jadex.jl/ . Please feel free to let me know if you run into any further issues!
